### ISSUE TITLE
Fix featured exhibits on home page

### ISSUE THREAD

**Issue by apjmason** [DigitalCarleton/mall-theme#1]
Homepage gives following error when there is no featured exhibit:
"Notice: Trying to get property of non-object in /var/www/cgmrdev/themes/mall-theme/index.php on line 12"

Fix by adding a check for empty here:
https://github.com/DigitalCarleton/mall-theme/blob/12847e36181a5eedcc1f1b19cb7a36115300c2c5/index.php#L12

Also, some exhibits don't seem to show. Try with multiple exhibits as featured and see what is broken.

**Comment by tutingjun** [comment]
Is there a placeholder background image I can use for the no featured exhibit section so that I can handle that error more gracefully? (instead of showing absolutely nothing) Or we just put a color background with text to handle the error.

**Comment by apjmason** [comment]
The /images directory contains theme specific images. There are some there from us that could work and some theme elements like bg.jpg that might work. 

That directory could probably be cleaned up to remove unneeded images from the mall history as well

**Comment by tutingjun** [comment]
I feel like the `bg.jpg` doesn't really work for the theme. Can I just add a roman image from google as a placeholder first and we can change it if we want?
