### ISSUE TITLE
mall map theming to match overall?

### ISSUE THREAD

**Issue by apjmason** [DigitalCarleton/mall-theme#11]
The yellow color on the walking tour map is different than the themes. Is the mall-map.css controlling those in the plugin? If so, we should think about how to reconcile without duplicating much work. 

See, for example, a details view or filter on [this page](https://omeka-dev-2022.carleton.edu/cgmrdev/map) 

![image](https://user-images.githubusercontent.com/10544799/206288648-1b824e20-b9d4-40ae-81df-84f7ed35b6e8.png)

**Comment by tutingjun** [comment]
Yes they are. I will add a pr and new branch in the mall map repo.

**Comment by tutingjun** [comment]
[Here](https://github.com/DigitalCarleton/MallMap/issues/9) is the new issue in map repo.

**Comment by tutingjun** [comment]
Fix nav bar color with this color scheme
<img width="794" alt="ColorSchemeforCGMRv3" src="https://user-images.githubusercontent.com/50512161/217376160-efe4d9c5-578b-40be-9816-9bb9f39cd28a.png">

**Comment by tutingjun** [comment]
Add shadow to the title text
