### ISSUE TITLE
Neatline stamen fix

### ISSUE THREAD

**Issue by apjmason** [DigitalCarleton/mall-theme#7]
Neatline stamen layers not loading correctly, due to bug, but Neatline no longer actively maintained. See e.g. [Houses and Gardens Tour](https://omeka-dev-2022.carleton.edu/cgmrdev/neatline/show/housesgardenstour).

Solution: Switch to [our fork](https://github.com/DigitalCarleton/Neatline), which contains a fix.

**Comment by tutingjun** [comment]
Update the plugin, [Houses and Gardens Tour](https://omeka-dev-2022.carleton.edu/cgmrdev/neatline/show/housesgardenstour) works.

**Comment by tutingjun** [comment]
Do we need to keep the git information inside the plugin?

**Comment by tutingjun** [comment]
TODO: Change it into a git clone

**Comment by tutingjun** [comment]
Add git support for the neatline plugin

**Comment by apjmason** [comment]
Switched our install in CGMR dev to our fork, since maintenance status of master unclear
